platform:ios,'8.0'
target 'LotteryProject' do
   pod 'Masonry'
   pod 'SDWebImage'
   pod 'MJRefresh'
   pod 'MJExtension'
   pod 'SVProgressHUD'
   pod 'ReactiveObjC', '~> 3.0.0'
   pod 'AFNetworking'
   
end
